### ISSUE TITLE
Unable to compile on Debian Stretch

### ISSUE THREAD

**Issue by magenbrot** [MonitoringPlug/monitoringplug#26]
Hi,

I can't compile the DNS check under Debian Stretch. 

Debian dropped the ldns-config tool with some package update: 
http://metadata.ftp-master.debian.org/changelogs/main/l/ldns/stable_changelog

`ldns (1.6.17-7) unstable; urgency=medium

  * Add lintian overrides for slightly errorneous man pages
  * Disable ldns-config distribution; please use pkg-config
  * Add missing dh-python B-D
  * Fix perl error in doxyparse.pl (Closes: #808665)`

I'm not a developer, so I can't help with switching to pkg-config.

**Comment by jiuka** [comment]
Should be fixed.
