### ISSUE TITLE
Do net fetch root keys from monitored host

### ISSUE THREAD

**Issue by heinlein-support** [MonitoringPlug/monitoringplug#29]
The plugin makes an DNS-query to the monitored host, asking also for the DNSKKEY for "." and the tld (".org"). 

In some cases the monitored host is an authoriative DNS server and doesn't serve recursive requests. Also not for its TLD. PowerDNS 4.x for example doesn't mix both functions in one system any more.

There's no need to fetch the root keys from the monitored host. Instead, they could/should be fetched from any DNS resolver that's defined in /etc/resolv.conf.

I'd prefere to

*) do this kind of requests against the default resolving system from the monitoring server
or
*) having a config switch to define, that also those keys should be fetched from the named host (for people who need this behavior for any reason).

Peer

**Comment by marieof9** [comment]
Hi Peer

I suppose you had this issu with the `check_dnssec_trace`, right? My though was to run this check against a resolver, not a authoritative server. However I separated the two revolvers. One for getting the domain under test and one for the tracing. Does the 29_use_separate_resolver branch work for you.

**Comment by heinlein-support** [comment]
Am 30.10.18 um 07:54 schrieb Marius Rieder:


Hi,

> I suppose you had this issu with the |check_dnssec_trace|, right? My
> though was to run this check against a resolver, not a authoritative
> server. However I separated the two revolvers. One for getting the

Yes, but it's also really perfect to check your own domain against your
authoritative DNS server to make sure, everything's up and running.

> domain under test and one for the tracing. Does the
> 29_use_separate_resolver branch work for you.

Thanks your your work, we will check hat in some days when our master of
monitoring :-) is back from holidays!

Peer

**Comment by gurubert** [comment]
Hi,
I can confirm that commit 759f1dcdb61e52395291071394d4ef67dffeb9e6 works for us.
Regards
