### ISSUE TITLE
Build Deps YACC

### ISSUE THREAD

**Issue by teadur** [MonitoringPlug/monitoringplug#31]
What package is required to be installed in debian buster for providing required build dep yacc ?

/bin/bash ../build-aux/ylwrap mp_template_yacc.y y.tab.c mp_template_yacc.c y.tab.h `echo mp_template_yacc.c | sed -e s/cc$/hh/ -e s/cpp$/hpp/ -e s/cxx$/hxx/ -e s/c++$/h++/ -e s/c$/h/` y.output mp_template_yacc.output -- yacc -d 
../build-aux/ylwrap: line 176: yacc: command not found
make[2]: *** [Makefile:993: mp_template_yacc.c] Error 127

only package providing binary with that name is:
/usr/lib/plan9/bin/yacc | 9base

but using it ends in fatal error: 
 fatal error:illegal comment, /build/monitoringplug/lib/mp_template_yacc.y:31

**Comment by teadur** [comment]
Using bison yacc like in build scripts ends in same results as #27

**Comment by jiuka** [comment]
Just use the source tarball from the github actions, or have alook on how to build the source tarball from the github actions config.

https://github.com/MonitoringPlug/monitoringplug/blob/master/.github/workflows/build.yml
