### ISSUE TITLE
Specify (deb-package) dependencies

### ISSUE THREAD

**Issue by Seegras** [MonitoringPlug/monitoringplug#32]
I had a hard time finding the necessary (Debian) dependencies for building everything. You should list them somewhere. Here they are, in the order reported by ./configure, for installing with apt: 

      - libcups2-dev
      - libcurl4-gnutls-dev
      - libldns-dev
      - libexpat1-dev
      - libfcgi-dev
      - libgnutls-openssl-dev
      - libopenipmi-dev
      - (should probably be libjson-c-dev but doesn't work)
      - libldap2-dev
      - libvirt-dev
      - libmysqlclient-dev
      - liboping-dev
      - libpq-dev
      - libhiredis-dev
      - libnfs-dev
      - libselinux1-dev
      - libsmbclient-dev
      - libsnmp-dev
      - libc6-dev
      - libvarnishapi-dev
      - libxmlrpc-core-c3-dev

**Comment by jiuka** [comment]
Is documented in [debian/control](https://github.com/MonitoringPlug/monitoringplug/blob/master/debian/control)
