### ISSUE TITLE
xsltproc specifies -nonet but also references a remote xslt file

### ISSUE THREAD

**Issue by thegushi** [MonitoringPlug/monitoringplug#33]
This seems to be something baked-in, not generated by autoconf -- it's right there in Makefile.am:

`DB2MAN = --xinclude -nonet http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl`

Net result of this is

```
Making all in doc
/usr/local/bin/xsltproc --xinclude -nonet http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl monitoringplug-eopt.xml
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
cannot parse http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
*** Error code 4
```

I'm not sure how this *ever* worked?

**Comment by Seegras** [comment]
For some reason ./configure --without-man doesn't seem to work anymore either..

**Comment by jiuka** [comment]
This works perfectly. On Ubuntu `docbook-xsl` needs to be installed. Or use a source package build in the github actions instead of git.
